name: Sync Branches
on:
    push:
        branches:
            - main
jobs:
    sync-3.2-90b:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source branch
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Checkout target branch
              run: git checkout preview/llama3.2-90b

            - name: Pull rebase
              run: git pull --rebase origin main

            - name: Push changes
              run: git push -f

    sync-3.1-8b:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source branch
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Checkout target branch
              run: git checkout preview/llama3.2-11b

            - name: Pull rebase
              run: git pull --rebase origin main

            - name: Push changes
              run: git push -f

    sync-3.2-11b:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source branch
              uses: actions/checkout@v2
              with:
                  ref: main

            - name: Checkout target branch
              run: git checkout preview/llama3.2-11b

            - name: Pull rebase
              run: git pull --rebase origin main

            - name: Push changes
              run: git push -f
